#!/usr/bin/python3

import argparse
import os
import subprocess

parser = argparse.ArgumentParser('evaluate_many')
parser.add_argument('folder', type=str, help='folder where the results are stored')
parser.add_argument('target', type=str, help='path to the target text')

args = parser.parse_args()

folder = args.folder
target = args.target

for fname in os.listdir(folder):
    _, ext = os.path.splitext(fname)
    if ext == '.txt':
        fpath = os.path.join(folder, fname)

        with open(fpath, 'rb') as f:
            evaluate_output = f.read()
        
        process = subprocess.run(['python3', 'scripts/evaluate.py', target], input=evaluate_output, stdout=subprocess.PIPE)

        print(process.stdout.decode().split(': ')[1].strip())
